import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import {Root} from "@/components/root/Root";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Root>{children}</Root>
}
